@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "",
  "receiverId": "656fc181a3fb2f705ea60ef3",
  "receiverUsername": "Luciano4",
  "receiverAvatarColor": "red",
  "receiverProfilePicture": "http://res.cloudinary.com/dhta9awgo/image/upload/v1699482975/654c0d5eb5d9c323b32a24b1",
  "body": "test",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}
