@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "6511f546dfe510c8e151fdb5",
  "postId": "6530724b699d159ab8547e03",
  "comment": "This is my second comment",
  "profilePicture": "http://res.cloudinary.com/dhta9awgo/image/upload/v1695675720/6511f546dfe510c8e151fdb5"
}

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/6530724b699d159ab8547e03
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/6530724b699d159ab8547e03/653072ef699d159ab8547e08
Content-Type: application/json
Accept: application/json
withCredentials: true
