@baseUrl = http://localhost:5000
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/user/follow/654c017e4f74b84fa0e1c046
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/654c017e4f74b84fa0e1c046/654c013e4f74b84fa0e1c03f
Content-Type: application/json
Accept: application/json
withCredentials: true

{}
